---

- hosts: all
  become: true
  tasks:
  - name: create user ansible
    tags: always
    user:
      name: ansible
      groups: root
  - name: add ssh key for ansible
    tags: always
    authorized_key:
      user: ansible
      key: <>
  - name: add sudoers file for ansible
    tags: always
    copy:
      src: ~/.ssh/Ansible/files/sudo_ansible 
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 440

